services:
  plex-delete-trash:
    build: .
    container_name: plex-delete-trash
    image:  plex-delete-trash
    restart: unless-stopped
    network_mode: bridge
    environment:
      - PLEX_URL="https://plex.evilminions.org:32400"
      - PLEX_TOKEN=7gYQs5NMuJGEq4vXGhyV
      - PLEX_IDLE_TIME_MIN=15
      - PLEX_CRON_SCHEDULE="* * * * *"

