services:
  plex-delete-trash:
    container_name: plex-delete-trash
    image: plex-delete-trash:latest
    restart: unless-stopped
    environment:
      - PLEX_TOKEN=<PLEX_TOKEN>
      - PLEX_URL=<PLEX_URL>
    labels:
      - diun.enable=true
